name: universite_qr_code
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.15.3
  intl: ^0.19.0
  shared_preferences: ^2.0.18
  firebase_core: ^2.7.0
  flutter_lints: ^2.0.0
  cloud_firestore: ^4.13.6
  flutter_plugin_tools: ^0.13.4+3
  flutter_native_splash: ^2.2.19
  flutter_screenutil: null
  get: ^4.6.6

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/Services-universitaires.png"



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/pngwing.com (11).png"

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700